from __future__ import annotations

import argparse
import json
import os
import platform
from pathlib import Path
import sys

from agentlib import command_version, find_root, git_snapshot, now_iso, parse_current

ROOT = Path(__file__).resolve().parents[1]


TOOLS = {
    "git": ["--version"],
    "gh": ["--version"],
    "rtk": ["--version"],
    "gortex": ["--version"],
    "python": ["--version"],
    "python3": ["--version"],
    "py": ["--version"],
    "node": ["--version"],
    "rg": ["--version"],
    "fd": ["--version"],
    "jq": ["--version"],
    "yq": ["--version"],
    "ast-grep": ["--version"],
    "docker": ["--version"],
}


def collect(root: Path) -> dict:
    adapters = {
        "AGENTS.md": (root / "AGENTS.md").exists(),
        "CLAUDE.md": (root / "CLAUDE.md").exists(),
        "GEMINI.md": (root / "GEMINI.md").exists(),
        "Cursor rule": (root / ".cursor/rules/00-universal-agent-kit.mdc").exists(),
        "Copilot": (root / ".github/copilot-instructions.md").exists(),
        "Windsurf": (root / ".windsurfrules").exists(),
        "Cline/Roo": (root / ".clinerules").exists(),
    }
    tools = {name: command_version(name, args) for name, args in TOOLS.items()}
    return {
        "generated_at": now_iso(),
        "root": str(root),
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "machine": platform.machine(),
            "python_runtime": sys.version.split()[0],
            "shell": os.environ.get("SHELL") or os.environ.get("ComSpec") or "-",
        },
        "git": git_snapshot(root),
        "current": parse_current(root),
        "adapters": adapters,
        "tools": tools,
    }


def markdown(data: dict) -> str:
    lines = [
        "# Agent doctor",
        "",
        f"- Generated: `{data['generated_at']}`",
        f"- Root: `{data['root']}`",
        f"- OS: `{data['platform']['system']} {data['platform']['release']} ({data['platform']['machine']})`",
        f"- Shell: `{data['platform']['shell']}`",
        "",
        "## Git",
    ]
    git = data["git"]
    if not git.get("is_repo"):
        lines.append("- Not a git repository.")
    else:
        lines += [
            f"- Branch: `{git.get('branch')}`",
            f"- HEAD: `{git.get('head')}`",
            f"- Dirty: `{git.get('dirty')}`",
        ]
        if git.get("status"):
            lines += ["", "```text", git["status"], "```"]
    lines += ["", "## Current task"]
    current = data.get("current") or {}
    if current:
        for key in ("ACTIVE_TASK", "STATUS", "BRANCH", "LAST_VERIFIED_COMMIT", "NEXT_ACTION"):
            if key in current:
                lines.append(f"- {key}: `{current[key]}`")
    else:
        lines.append("- No readable `.agents/state/CURRENT.md`.")
    lines += ["", "## Tools"]
    for name, info in data["tools"].items():
        if info.get("available"):
            lines.append(f"- {name}: `{info.get('version')}`")
        else:
            lines.append(f"- {name}: absent")
    lines += ["", "## Adapters"]
    for name, present in data["adapters"].items():
        lines.append(f"- {name}: {'present' if present else 'missing'}")
    return "\n".join(lines) + "\n"


def write_local(root: Path, data: dict) -> Path:
    tools = data["tools"]
    def ver(name: str) -> str:
        info = tools.get(name, {})
        return info.get("version", "absent") if info.get("available") else "absent"
    path = root / "AGENT.local.md"
    content = f"""# Local agent environment

- Generated: {data['generated_at']}
- OS: {data['platform']['system']} {data['platform']['release']} ({data['platform']['machine']})
- Shell: {data['platform']['shell']}
- Python: {data['platform']['python_runtime']}
- Profile: balanced
- RTK: {ver('rtk')}
- Gortex: {ver('gortex')}
- GitHub CLI: {ver('gh')}
- Ripgrep: {ver('rg')}
- Shared agent cache: `.agent-cache`
- Network constraints: unknown
- Notes: generated by `scripts/agent_doctor.py`; no secrets

This file is local and ignored. Never put secrets here.
"""
    path.write_text(content, encoding="utf-8", newline="\n")
    return path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--write-local", action="store_true")
    args = parser.parse_args()
    root = find_root(args.root)
    data = collect(root)
    if args.write_local:
        path = write_local(root, data)
        data["local_file"] = str(path)
    print(json.dumps(data, ensure_ascii=False, indent=2) if args.json else markdown(data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
